### ISSUE TITLE
Referenced this lib from the R.swift docs

### ISSUE THREAD

**Issue by mac-cain13** [Nirma/UIFontComplete#10]
Not so much an issue, but I wanted to give you an heads up that I just referenced this nice library from the [R.swift documentation](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Examples.md#custom-fonts). We had an open [feature request](https://github.com/mac-cain13/R.swift/issues/115) for a while, but this seperate library seems to be a better fit then to build it into R.swift.

For custom fonts R.swift detects the font family and generates a reference for you so you don't need to know anything about the font family string, but for system fonts we do nothing. So I think this lib would fill that gap for our users. Thanks for creating it!

**Comment by Nirma** [comment]
@mac-cain13 Thanks for referencing it!

Sure Im happy thay it fills a need and if there is anything that feels off about the library or 
a feature request that anyone needs, please feel free to open an issue!
