### ISSUE TITLE
Update for Swift 4 please

### ISSUE THREAD

**Issue by MKGitHub** [Nirma/UIFontComplete#19]
Update for Swift 4 please

**Comment by Nirma** [comment]
@MKGitHub Thank you for opening the issue!

I have created a branch `swift_4` so please target that branch for swift 4 development. 
After Swift 4 is released I plan to merge `swift_4` into master.

The pull request is here #20

**Comment by Nirma** [comment]
Swift 4 integration is done, closing this one.
