### ISSUE TITLE
can not find the method in UIFont extension

### ISSUE THREAD

**Issue by sishenyihuba** [Nirma/UIFontComplete#3]
Hi Norma:

I find that the main ViewController can not find the convenience init method in UIFont extension when using CoCoaPods.  I wonder weather or not apple have change the access level in extension when using "puclib" key word.

<img width="1017" alt="font demo" src="https://cloud.githubusercontent.com/assets/7836659/25110839/9a590310-2419-11e7-9098-97e384441cc2.png">

**Comment by jrtibbetts** [comment]
Of course you didn't find it--you didn't `import UIFontComplete` at the top of your file.

**Comment by sishenyihuba** [comment]
ehhhh….  Extension stuff should import the Modual too?  Sorry for that mistake.

**Comment by Nirma** [comment]
@jrtibbetts Thanks for answering the question! 💯 

@sishenyihuba Thanks for raising the issue! after importing with `import UIFontComplete` 
can you use the library now?
