### ISSUE TITLE
if I add custom font with FontRepresentable protocol, I can not have 2 those types(Font, CutomFont) in one array

### ISSUE THREAD

**Issue by bizibizi** [Nirma/UIFontComplete#32]
Because of error: Protocol can only be used as a generic constraint because it has Self or associated type requirements

**Comment by bizibizi** [comment]
Enum CustomFont: String, FontRepresentable {
 case Lalalla = "Lalalla"
}

let array =  [FontRepresentable]      <- error

**Comment by Nirma** [comment]
@bizibizi Thanks for opening this issue! Im looking into it now!

**Comment by jrtibbetts** [comment]
That's exactly as it should be. `FontRepresentable`'s only implementation is for `Strings, so you have two options if you want to put them in arrays:

1. Use an array of font names:

```
var fontNames = ["Lalalla", "Helvetica"]
```

And then use those strings to create your fonts:

```
let firstFont = fontNames[0].of(size: 20.0)
```

2. Use an array of fonts created from those names:

```
var fonts = ["Lalalla".of(size: 20.0), Font.americanTypewriter.of(size(20.0))]
```

As a side note, now that I see `of(size:)` being used with bare strings, it's entirely unclear what it's doing. [I should have called it](https://github.com/Nirma/UIFontComplete/pull/4) `font(ofSize:)`.
