### ISSUE TITLE
SF Symbols

### ISSUE THREAD

**Issue by Nirma** [Nirma/UIFontComplete#35]
Should there be any updates to support SF symbols?

**Comment by thisIsTheFoxe** [comment]
afaik you cannot use SF Symbols as a 'font'. It's **a part of** other San Francisco fonts. You can however, use it as an NSAttributedString-attachment e.g. [in a label](https://stackoverflow.com/questions/58341042/is-it-possible-to-use-sf-symbols-outside-of-uiimage) .-.

**Comment by Nirma** [comment]
@thisIsTheFoxe Yeah this seems about right, I was thinking along the lines of defining symbol names somewhere but maybe its best left as is.
