### ISSUE TITLE
FREE YouTube VIDEO TUTORIAL

### ISSUE THREAD

**Issue by rebeloper** [Nirma/UIFontComplete#37]
Hi,
Love UIFontComplete. So I made a 25 minutes long YouTube tutorial explaining it: https://youtu.be/JegutXcer60

Feel free to add it to the README / Documentation / Cheat Sheet with this image [people tap on images more than on boring links :) ]
![EasyUIFont](https://user-images.githubusercontent.com/2488011/86817453-ba7e9100-c08d-11ea-990b-9dcfaf9eaa69.png)

Hope you like it. I'm open to any feedback.

**Comment by Nirma** [comment]
@rebeloper Thanks so much! I know this reply is a bit late but sure how about sending a pull request over to add that section to the `README.md`?

By the way what do you think of my new lightweight HTTP library? https://github.com/Nirma/Mu

I am trying to show it some love!
